tournament:
  games: 5
  concurrency: 2
  tc: "1+0.1"

engines:
  - name: MyEngine
    cmd: bin/my_engine

  - name: Stockfish
    cmd: bin/stockfish

    options:
      UCI_LimitStrength: "true"
      UCI_Elo: 1800
      Skill Level: 10