tournament:
  games: 3
  concurrency: 1
  tc: "5+0.1"

  opening:
    file: "resources/opening/8moves_v3.pgn"
    format: "pgn"
    order: "random"
    plies: 8

engines:
  - name: MyEngine
    cmd: bin/my_engine

  - name: Stockfish
    cmd: bin/stockfish-mac

    options:
      UCI_LimitStrength: "true"
      UCI_Elo: 1320
      Skill Level: 0